### ISSUE TITLE
makedir issues

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#40] opened 2019-10-28 09:32 UTC
The trailing slash seems to make trouble...

**Comment by sodero** [comment] 2019-10-28 11:56
Will look into it. Is this affecting both Roadshow and Deluxe music?

**Comment by sodero** [comment] 2019-10-28 15:13
Roadshow is using (trap). Is that also the case with Deluxe music? That's just a stub in InstallerLG since it did not seem to work in the CBM installer. I need to look deeper into what the CBM installer (trap) statement does.

**Comment by polluks** [comment] 2019-10-29 08:51
![dmcs](https://user-images.githubusercontent.com/4707573/67751553-9d3ef080-fa31-11e9-9511-e3027dbaf1b9.png)
Line 0?
[Install-DeluxeMusic.txt](https://github.com/sodero/InstallerLG/files/3782488/Install-DeluxeMusic.txt)

**Comment by sodero** [comment] 2019-10-29 12:56
Line 0 is seriously broken. Thanks, will look into it.

**Comment by sodero** [comment] 2019-10-30 20:15
Fixed.

**Comment by sodero** [comment] 2019-10-30 20:20
Bah! It's leaking memory, crap.

**Comment by sodero** [comment] 2019-10-30 21:51
Ok, silly misstake. Fixed now.

**Comment by polluks** [comment] 2019-11-07 12:26
![dmcs2](https://user-images.githubusercontent.com/4707573/68388940-0c1ef680-0162-11ea-8ea5-4702682b8200.png)
Strange...

**Comment by sodero** [comment] 2019-11-07 13:39
Wierd, are your file permissions OK?

**Comment by sodero** [comment] 2019-11-07 13:40
Will try to reproduce it tonight.

**Comment by polluks** [comment] 2019-11-07 14:09
BTW you see the German catalog because the system one (with the same name) is now ignored :)

**Comment by sodero** [comment] 2019-11-07 21:23
I'm having trouble reproducing this on AROS (found a problem with CRLF / CR contaminated files though, because of me downloading the *.txt script above on Windows).

Does 'Applications' on DH3: exist before you run the script?
Is 'Applications' write-protected?
Does it make any difference if you change (makedir app_path (infos)) to just (makedir app_path)?

**Comment by polluks** [comment] 2019-11-07 22:58
I also tried T:, no difference without (infos).

**Comment by sodero** [comment] 2019-11-07 23:06
Ok, I'll test with MorphOS instead.

**Comment by polluks** [comment] 2019-11-07 23:15
Thanks, however I see no fail with Snoopium...

**Comment by sodero** [comment] 2019-11-10 13:38
I've struggled to reproduce this on MorphOS as well, but failed for some reason.

I did (makedir) more forgiving though. Maybe it works for you now?

If not, can you add (debug app_path) before (makedir) on line 302 and run from shell and see what the output is?

Can you also do a "list all" in DH3: to show all file / dir permissions?

**Comment by sodero** [comment] 2019-11-10 13:40
BTW, when running Snoopy, did you tick all the checkboxes?

**Comment by polluks** [comment] 2019-11-10 14:27
Finally it works!

**Closed** 2019-11-10 14:44 UTC
