### ISSUE TITLE
MUIbase 4.1 installer fails

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#32] opened 2019-03-11 22:19 UTC
(protect (tackon #destination "MUIbase") "+rwed")
![MUIbase](https://i.ibb.co/wBKfzrs/MUIbase.png)
````
[49:run] Executed 'C:Version >NIL: MorphOS'.
[598:makedir] Created 'New_Work:Applications/MUIbase'.
[608:makedir] Created 'New_Work:Applications/MUIbase/Include'.
[618:makedir] Created 'New_Work:Applications/MUIbase/Projects'.
[631:copyfiles] Directory 'New_Work:Applications/MUIbase' exists already.
[631:copyfiles] Get mask '' 2
[631:copyfiles] Protect 'New_Work:Applications/MUIbase' 2
[631:copyfiles] Copied 'LiesMich' to 'New_Work:Applications/MUIbase/LiesMich'.
[631:copyfiles] Get mask 'LiesMich' 0
[631:copyfiles] Protect 'New_Work:Applications/MUIbase/LiesMich' 0
[650:copyfiles] Directory 'New_Work:Applications/MUIbase' exists already.
[650:copyfiles] Get mask 'MUIbase-ppc-morphos' 0
[650:copyfiles] Protect 'New_Work:Applications/MUIbase' 0
[651:protect] Get mask 'New_Work:Applications/MUIbase/MUIbase' -1
````

**Comment by sodero** [comment] 2019-03-12 11:32
Thanks for reporting this! Will be fixed shortly, busy schedule right now but I'll do my best.

**Comment by sodero** [comment] 2019-03-12 21:07
I couldn't reproduce this problem on AROS. Will try on MorphOS.

**Comment by sodero** [comment] 2019-03-15 08:37
I couldn't reproduce this on MorphOS either. Could you provide some more details, like from where you're running the scripts, file and dir permissions and so on?

I did discover another problem though; there is something fishy about how local variables are handeled that causes infinite recursion further down...

**Comment by polluks** [comment] 2019-03-15 09:19
Ok, by the way it was a PFS partition.

**Comment by sodero** [comment] 2019-03-15 09:21
Ah, PFS, I'll see what I can do...

**Comment by sodero** [comment] 2019-03-25 19:18
Does it work for you now?

**Comment by polluks** [comment] 2019-03-26 14:44
No icons are copied but `Project.info`.

**Comment by sodero** [comment] 2019-03-26 19:05
Ok, thanks! I'll look into it.

**Comment by sodero** [comment] 2019-03-29 21:04
Fixed.

**Closed** 2019-03-30 19:20 UTC
